steamKey: 8F1AAF91A2EFD818C6A967E7565C183D
mods:
  - screepsmod-auth
  - screepsmod-admin-utils
bots:
  simplebot: screepsbot-zeswarm
serverOptions:
  logConsole: true
serverConfig:
  welcomeText: |
    <h1 style="text-align: center;">LKlaus Hosting Server</h1>
  tickRate: 1000
