mods:
  - screepsmod-auth
  - screepsmod-admin-utils
bots:
  simplebot: screepsbot-zeswarm
serverConfig:
  welcomeText: |
    <h1 style="text-align: center;">LKlaus Hosting Server</h1>
  tickRate: 1000
