steamKey: 8F1AAF91A2EFD818C6A967E7565C183D
mods:
  - screepsmod-auth
  - screepsmod-admin-utils
bots:
  simplebot: screepsbot-zeswarm
serverConfig:
  welcomeText: |
    <h1 style="text-align: center;">My Cool Server</h1>
  constants:
    TEST_CONSTANT: 123
  tickRate: 1500
