FROM mongo:7.0.2

RUN mkdir /opt/screeps

WORKDIR /opt/screeps

RUN apt update && apt install -y build-essential tcl git python redis git
RUN curl -L https://github.com/screepers/screeps-launcher/releases/download/v1.15.1/screeps-launcher_v1.15.1_linux_amd64 > screeps-launcher
RUN chmod +x screeps-launcher

RUN git clone git@github.com:Lela810/Screeps-Egg.git

COPY /opt/screeps/Screeps-Egg/src/screeps-launcher.service /etc/systemd/system/screeps-launcher.service

RUN systemctl daemon-reload
RUN systemctl enable screeps-launcher

