steamKey:
mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo
bots:
  simplebot: screepsbot-zeswarm
serverConfig:
  welcomeText: |
    <h1 style="text-align: center;">My Cool Server</h1>
  constants:
    TEST_CONSTANT: 123
  tickRate: 1500
